echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "ssss"
echo "hghjgkj"
echo "hghj"
echo "we are trying to help you"
echo "we are creating merge conflict to learn how to solve it"
echo "i am from batch 20"